REM =======================================================
REM Run this scripts as ADMIN at your Oracle Free Tier OCI
REM =======================================================

SET ECHO OFF
SET VERIFY OFF

--create users
CREATE USER DEV IDENTIFIED BY "Qwerty12345$";
ALTER USER DEV DEFAULT TABLESPACE DATA TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK ;
ALTER USER DEV QUOTA UNLIMITED ON DATA;

CREATE USER UAT IDENTIFIED BY "Qwerty12345$";
ALTER USER UAT DEFAULT TABLESPACE DATA TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK ;
ALTER USER UAT QUOTA UNLIMITED ON DATA;


--works for OCI Cloud
GRANT DWROLE TO DEV;
GRANT DWROLE TO UAT;

/*If you want to create it at on-premise db use below scripts
GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO &username;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE , UNLIMITED TABLESPACE TO &username;
*/